### PR TITLE
add package.json with npm requirements and update README to reflect

### PR DESCRIPTION
**Pull request by davidsneighbour**
- adding node_modules to gitignore
- adding postcss-cli to local npm requirements
- add initial package.json
- add add package-lock.json with current versioning

Note: the author line in package.json should reflect something like "Name <Email>" in the end, but I am not sure what to add there. Feel free to correct.

### CODE REVIEW

**Comment by davidsneighbour** [comment]
> 11:57:50 PM: Installing NPM modules using NPM version 3.10.10

in the Netlify docs has an utterly old version number... any idea why?

**Comment by bep** [comment]
> any idea why?

The version of "things" in Netlify is connected to

1. The build image used
2. The time you created the site. You can update by setting `GO_VERSION` etc. env var, but they don't want to break existing sites.

**Comment by davidsneighbour** [comment]
This would be something _you_ have to do (I am just pushing and your netlify team is creating previews). Please set `NPM_VERSION` to `6.13.4` in your docuapi environment and see if that solves the issue. If not, I will test locally tomorrow. 

The log of the deploys is cutting off in the middle of installing packages, so something is going on there. Maybe adding debug parameters to the build command for dev environments will show more info.

**Comment by bep** [comment]
I have bumped the NPM version and triggered a rebuild.

**Comment by davidsneighbour** [comment]
perfect. working now. don't forget to add your authorinfo to package.json before merging.

**Pull request merged**
